/* ===================== Base de données des cultures ===================== */
/* Données simplifiées à but de démonstration (unités agronomiques indicatives) */

const CROPS = [
    {
      slug: "poire",
      name: "الإجاص",
      emoji: "🍐",
      category: "fruit",
      tempMin: 15, tempMax: 30,
      humidityMin: 50, humidityMax: 70,
      rainMin: 600, rainMax: 900,
      irrigation: "متوسط",
      lifeCycle: "معمر",
      labor: "عالي",
      plantingMethod: "تمت زراعته بالتشتيل",
      phMin: 6, phMax: 7,
      soilType: "طباشيري",
      rowSpacing: "6-8 m",
      plantSpacing: "4 m",
      npk: { n: [100, 130], p: [27, 36], k: [190, 250] },
      unit: "شجرة",
      companionGood: ["قمح"],
      companionBad: ["التفاح", "التوت البري", "الكرز"],
    },
    {
      slug: "basala",
      name: "البصل", emoji: "🧅", category: "légume",
      tempMin: 13, tempMax: 28, humidityMin: 55, humidityMax: 75,
      rainMin: 350, rainMax: 600, irrigation: "منتظم",
      lifeCycle: "حولي", labor: "متوسط", plantingMethod: "تمت زراعته بالبذر المباشر",
      phMin: 6, phMax: 7, soilType: "رملية طينية",
      rowSpacing: "30-40 cm", plantSpacing: "10 cm",
      npk: { n: [60, 90], p: [30, 45], k: [80, 110] }, unit: "م²",
      companionGood: ["الجزر", "الطماطم"], companionBad: ["البازيلاء", "الفاصوليا"],
    },
    {
      slug: "batata",
      name: "البطاطا", emoji: "🥔", category: "légume",
      tempMin: 15, tempMax: 24, humidityMin: 60, humidityMax: 80,
      rainMin: 500, rainMax: 700, irrigation: "منتظم",
      lifeCycle: "حولي", labor: "متوسط", plantingMethod: "تمت زراعته بالدرنات",
      phMin: 5, phMax: 6.5, soilType: "رملية",
      rowSpacing: "70-90 cm", plantSpacing: "30 cm",
      npk: { n: [90, 120], p: [40, 60], k: [120, 160] }, unit: "م²",
      companionGood: ["الذرة", "الفول"], companionBad: ["الطماطم", "الخيار"],
    },
    {
      slug: "batikh",
      name: "البطيخ", emoji: "🍉", category: "fruit",
      tempMin: 22, tempMax: 32, humidityMin: 50, humidityMax: 70,
      rainMin: 400, rainMax: 600, irrigation: "عالي",
      lifeCycle: "حولي", labor: "متوسط", plantingMethod: "تمت زراعته بالبذر المباشر",
      phMin: 6, phMax: 6.8, soilType: "رملية",
      rowSpacing: "2-2.5 m", plantSpacing: "80 cm",
      npk: { n: [80, 110], p: [35, 50], k: [140, 180] }, unit: "نبتة",
      companionGood: ["الذرة"], companionBad: ["البطاطا"],
    },
    {
      slug: "dhora",
      name: "الذرة", emoji: "🌽", category: "céréale",
      tempMin: 18, tempMax: 30, humidityMin: 50, humidityMax: 75,
      rainMin: 450, rainMax: 700, irrigation: "متوسط",
      lifeCycle: "حولي", labor: "منخفض", plantingMethod: "تمت زراعته بالبذر المباشر",
      phMin: 5.8, phMax: 7, soilType: "طينية رملية",
      rowSpacing: "70-80 cm", plantSpacing: "25 cm",
      npk: { n: [120, 160], p: [40, 55], k: [60, 90] }, unit: "م²",
      companionGood: ["الفاصوليا", "اليقطين"], companionBad: [],
    },
    {
      slug: "khiar",
      name: "الخيار", emoji: "🥒", category: "légume",
      tempMin: 18, tempMax: 28, humidityMin: 60, humidityMax: 80,
      rainMin: 400, rainMax: 600, irrigation: "عالي",
      lifeCycle: "حولي", labor: "متوسط", plantingMethod: "تمت زراعته بالتشتيل",
      phMin: 5.5, phMax: 6.8, soilType: "خصبة جيدة الصرف",
      rowSpacing: "1-1.5 m", plantSpacing: "40 cm",
      npk: { n: [70, 100], p: [30, 45], k: [110, 150] }, unit: "نبتة",
      companionGood: ["الذرة", "البازيلاء"], companionBad: ["البطاطا"],
    },
    {
      slug: "tamatem",
      name: "الطماطم", emoji: "🍅", category: "légume",
      tempMin: 18, tempMax: 27, humidityMin: 50, humidityMax: 70,
      rainMin: 400, rainMax: 600, irrigation: "منتظم",
      lifeCycle: "حولي", labor: "عالي", plantingMethod: "تمت زراعته بالتشتيل",
      phMin: 6, phMax: 6.8, soilType: "طينية رملية",
      rowSpacing: "80-100 cm", plantSpacing: "40 cm",
      npk: { n: [100, 140], p: [40, 60], k: [150, 200] }, unit: "نبتة",
      companionGood: ["البصل", "الجزر"], companionBad: ["البطاطا"],
    },
    {
      slug: "felfel",
      name: "الفلفل", emoji: "🌶️", category: "légume",
      tempMin: 20, tempMax: 30, humidityMin: 55, humidityMax: 75,
      rainMin: 400, rainMax: 600, irrigation: "منتظم",
      lifeCycle: "حولي", labor: "متوسط", plantingMethod: "تمت زراعته بالتشتيل",
      phMin: 5.8, phMax: 6.8, soilType: "طينية رملية",
      rowSpacing: "60-80 cm", plantSpacing: "35 cm",
      npk: { n: [90, 120], p: [35, 50], k: [120, 160] }, unit: "نبتة",
      companionGood: ["الباذنجان"], companionBad: ["الفاصوليا"],
    },
    {
      slug: "bathenjan",
      name: "الباذنجان", emoji: "🍆", category: "légume",
      tempMin: 20, tempMax: 30, humidityMin: 55, humidityMax: 75,
      rainMin: 450, rainMax: 650, irrigation: "منتظم",
      lifeCycle: "حولي", labor: "متوسط", plantingMethod: "تمت زراعته بالتشتيل",
      phMin: 5.5, phMax: 6.8, soilType: "طينية رملية",
      rowSpacing: "70-90 cm", plantSpacing: "45 cm",
      npk: { n: [100, 130], p: [40, 55], k: [130, 170] }, unit: "نبتة",
      companionGood: ["الفلفل"], companionBad: [],
    },
    {
      slug: "aruz",
      name: "الأرز", emoji: "🌾", category: "céréale",
      tempMin: 20, tempMax: 32, humidityMin: 70, humidityMax: 90,
      rainMin: 1000, rainMax: 1500, irrigation: "غمر",
      lifeCycle: "حولي", labor: "عالي", plantingMethod: "تمت زراعته بالشتل",
      phMin: 5.5, phMax: 6.5, soilType: "طينية",
      rowSpacing: "20-25 cm", plantSpacing: "15 cm",
      npk: { n: [100, 140], p: [30, 40], k: [40, 60] }, unit: "م²",
      companionGood: [], companionBad: [],
    },
    {
      slug: "bamia",
      name: "البامية", emoji: "🫛", category: "légume",
      tempMin: 22, tempMax: 32, humidityMin: 50, humidityMax: 70,
      rainMin: 400, rainMax: 600, irrigation: "متوسط",
      lifeCycle: "حولي", labor: "منخفض", plantingMethod: "تمت زراعته بالبذر المباشر",
      phMin: 6, phMax: 6.8, soilType: "رملية طينية",
      rowSpacing: "60-70 cm", plantSpacing: "30 cm",
      npk: { n: [70, 100], p: [30, 40], k: [90, 120] }, unit: "م²",
      companionGood: ["الفلفل"], companionBad: [],
    },
    {
      slug: "basela",
      name: "البسلة", emoji: "🫘", category: "légumineuse",
      tempMin: 12, tempMax: 22, humidityMin: 55, humidityMax: 75,
      rainMin: 350, rainMax: 550, irrigation: "متوسط",
      lifeCycle: "حولي", labor: "منخفض", plantingMethod: "تمت زراعته بالبذر المباشر",
      phMin: 6, phMax: 7, soilType: "طينية رملية",
      rowSpacing: "40-50 cm", plantSpacing: "8 cm",
      npk: { n: [20, 35], p: [30, 45], k: [60, 90] }, unit: "م²",
      companionGood: ["الذرة", "الخيار"], companionBad: ["البصل", "الثوم"],
    },
  ];
  
  function getCropBySlug(slug){
    return CROPS.find(c => c.slug === slug) || CROPS[0];
  }